In [1]:
from pandas_profiling import ProfileReport
import pandas as pd
from pycaret.classification import *


df = pd.read_excel("Data Uni Dissertation.xlsx")

report = ProfileReport(df)
report.to_file(output_file= "report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# titulo
## titulo
### titulo

In [3]:
exp_name = setup(data = df, target = "desertion")

In [4]:
best_model = compare_models()